#!/bin/bash

if [[ -z "$APPDIR" ]]; then
  APPDIR="$(dirname "$(readlink -f "${0}")")"
fi

export LD_LIBRARY_PATH="$APPDIR/usr/lib:$LD_LIBRARY_PATH"
export SRCDIR="$PWD"

# If this is ChromeOS...
if [[ -f "/sys/devices/virtual/dmi/id/product_name" ]]; then
  if [[ $(cat /sys/devices/virtual/dmi/id/product_name) == "crosvm" ]]; then  
    # and the program needs to be scaled for a HiDPI display...
    if DISPLAY=:1 xset q &>/dev/null; then
      export DISPLAY=:1
    fi
  fi
fi

if [[ -f "$APPDIR/usr/bin/steamshim" ]]; then
  # Run Steamshim process
  exec "$APPDIR/usr/bin/steamshim"
else
  # Run mkxp-z process
  exec "$APPDIR/usr/bin/mkxp-z"
fi
