name: Build

on:
  push:
    branches:
    - dev
    paths:
    - '.github/workflows/autobuild.yml'
    - 'src/**'
    - 'binding/**'
    - 'shader/**'
    - 'assets/**'
    - 'windows/**'
    - 'linux/**'
    - 'macos/**'
    - 'meson.build'
    - 'meson_options.txt'

  pull_request:
    branches:
    - dev
    paths:
    - '.github/workflows/autobuild.yml'
    - 'src/**'
    - 'binding/**'
    - 'shader/**'
    - 'assets/**'
    - 'windows/**'
    - 'linux/**'
    - 'macos/**'
    - 'meson.build'
    - 'meson_options.txt'

  workflow_dispatch:

jobs:
  build-windows:
    name: Windows (${{ matrix.sys }})
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        include:
        - { sys: mingw32, env: i686, ruby-prefix: msvcrt }
        - { sys: mingw64, env: x86_64, ruby-prefix: x64-msvcrt }
        - { sys: ucrt64, env: ucrt-x86_64, ruby-prefix: x64-ucrt }

    steps:
      - name: Shorten commit SHA
        id: shorten-sha
        uses: benjlevesque/short-sha@v2.2
        with:
          length: 7

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSYS2 (${{ matrix.sys }})
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.sys }}
          install: >-
            base-devel
            git
            ruby
            vim
            mingw-w64-${{ matrix.env }}-autotools
            mingw-w64-${{ matrix.env }}-cmake
            mingw-w64-${{ matrix.env }}-gcc
            mingw-w64-${{ matrix.env }}-meson

      - name: Dependencies cache
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: windows/build-${{ matrix.sys }}
          key: windows-${{ matrix.sys }}-${{ hashFiles('windows/Makefile') }}

      - name: Build dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        shell: msys2 {0}
        working-directory: ${{ github.workspace }}/windows
        run: make LTO=0

      - name: Build mkxp-z
        shell: msys2 {0}
        run: |
          source windows/vars.sh
          meson setup build
          meson compile -Cbuild

      - name: Prepare artifact
        shell: msys2 {0}
        run: |
          mkdir -v build/artifact
          cp -v build/mkxp-z.exe build/artifact/
          cp -v windows/build-${{ matrix.sys }}/bin/${{ matrix.ruby-prefix }}-ruby310.dll build/artifact/
          cp -vr windows/build-mingw64/lib/ruby/3.1.0 build/artifact/rubylib
          cp -v mkxp.json build/artifact/
          cp -vr scripts build/artifact/scripts
          strip -S -x build/artifact/mkxp-z.exe
          strip -S -x build/artifact/${{ matrix.ruby-prefix }}-ruby310.dll

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: mkxp-z-Windows-${{ matrix.sys }}-${{ github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name }}-${{ steps.shorten-sha.outputs.sha }}
          path: build/artifact

  build-ubuntu-20:
    name: Ubuntu 20.04
    runs-on: ubuntu-20.04

    steps:
      - name: Shorten commit SHA
        id: shorten-sha
        uses: benjlevesque/short-sha@v2.2
        with:
          length: 7

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y wget git vim ruby python3 python3-pip build-essential autoconf automake libtool pkg-config cmake bison libgl1-mesa-dev xorg-dev libxext-dev libasound2-dev libpulse-dev
          sudo python3 -m pip install meson ninja

      - name: Install Autoconf 2.71
        working-directory: ${{ runner.temp }}
        run: |
          wget https://ftp.gnu.org/gnu/autoconf/autoconf-2.71.tar.xz
          tar -xf autoconf-2.71.tar.xz
          cd autoconf-2.71
          ./configure
          make -j2
          sudo make install

      - name: Dependencies cache
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: linux/build-x86_64
          key: linux-x86_64-${{ hashFiles('linux/Makefile') }}

      - name: Build dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        working-directory: ${{ github.workspace }}/linux
        run: make LTO=0

      - name: Build mkxp-z
        run: |
          source linux/vars.sh
          meson build --bindir=. --prefix=$GITHUB_WORKSPACE/build/artifact
          meson compile -Cbuild
          meson install -Cbuild

      - name: Prepare artifact
        run: |
          cp -vr linux/build-x86_64/lib/ruby/3.1.0 build/artifact/rubylib
          cp -v mkxp.json build/artifact/
          cp -vr scripts build/artifact/scripts
          strip -S -x build/artifact/mkxp-z.x86_64
          strip -S -x build/artifact/lib64/libruby.so.3.1

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: mkxp-z-Ubuntu-20.04-${{ github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name }}-${{steps.shorten-sha.outputs.sha}}
          path: build/artifact

  build-macos:
    name: macOS
    runs-on: macos-latest

    steps:
      - name: Shorten commit SHA
        id: shorten-sha
        uses: benjlevesque/short-sha@v2.2
        with:
          length: 7

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove pre-existing Homebrew packages
        run: brew remove --force $(brew list)

      - name: Install Homebrew tools
        working-directory: ${{ github.workspace }}/macos/Dependencies
        run: brew bundle

      - name: Dependencies cache
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: |
            macos/Dependencies/build-macosx-x86_64
            macos/Dependencies/build-macosx-arm64
            macos/Dependencies/build-macosx-universal
          key: macos-${{ hashFiles('macos/Dependencies/*.make', 'macos/Dependencies/*.sh') }}

      - name: Build dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        working-directory: ${{ github.workspace }}/macos/Dependencies
        run: ./setup.sh

      - name: Build mkxp-z
        working-directory: ${{ github.workspace }}/macos
        run: xcodebuild -project mkxp-z.xcodeproj -configuration "Release" -scheme "Universal" -derivedDataPath "$GITHUB_WORKSPACE/build"

      - name: Compress artifact
        working-directory: ${{ github.workspace }}/build/Build/Products/Release
        run: ditto -c -k --sequesterRsrc --keepParent Z-universal.app Z-universal.app.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: mkxp-z-macOS-${{github.event_name == 'pull_request' && format('PR{0}', github.event.number) || github.ref_name}}-${{steps.shorten-sha.outputs.sha}}
          path: build/Build/Products/Release/Z-universal.app.zip
